[project]
name = "SWE_Aufgabe_5"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "he4116", email = "he4116@mci4me.at"},
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
